main() => 1?.{;
main() => 1?. 1; };
main() => 1?.=> ;
main() => 1?.( {};
main() => 1?.) { 1; };
main() => 1?.(p) => ;
main() => 1?.(p) {;
main() => 1?.(p) 1; };
main() => 1?.(int p) => ;
main() => 1?.(int p) {;
main() => 1?.(int p) 1; };
