include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - unnecessary_type_name_in_constructor
    - unnecessary_const_in_enum_constructor
    - unawaited_futures
