typedef void abstract();
typedef abstract = void Function();
typedef void as();
typedef as = void Function();
typedef void assert();
typedef assert = void Function();
typedef void async();
typedef async = void Function();
typedef void await();
typedef await = void Function();
typedef void break();
typedef break = void Function();
typedef void case();
typedef case = void Function();
typedef void catch();
typedef catch = void Function();
typedef void class();
typedef class = void Function();
typedef void const();
typedef const = void Function();
typedef void continue();
typedef continue = void Function();
typedef void covariant();
typedef covariant = void Function();
typedef void default();
typedef default = void Function();
typedef void deferred();
typedef deferred = void Function();
typedef void do();
typedef do = void Function();
typedef void dynamic();
typedef dynamic = void Function();
typedef void else();
typedef else = void Function();
typedef void enum();
typedef enum = void Function();
typedef void export();
typedef export = void Function();
typedef void extends();
typedef extends = void Function();
typedef void extension();
typedef extension = void Function();
typedef void external();
typedef external = void Function();
typedef void factory();
typedef factory = void Function();
typedef void false();
typedef false = void Function();
typedef void final();
typedef final = void Function();
typedef void finally();
typedef finally = void Function();
typedef void for();
typedef for = void Function();
typedef void Function();
typedef Function = void Function();
typedef void get();
typedef get = void Function();
typedef void hide();
typedef hide = void Function();
typedef void if();
typedef if = void Function();
typedef void implements();
typedef implements = void Function();
typedef void import();
typedef import = void Function();
typedef void in();
typedef in = void Function();
typedef void inout();
typedef inout = void Function();
typedef void interface();
typedef interface = void Function();
typedef void is();
typedef is = void Function();
typedef void late();
typedef late = void Function();
typedef void library();
typedef library = void Function();
typedef void mixin();
typedef mixin = void Function();
typedef void native();
typedef native = void Function();
typedef void new();
typedef new = void Function();
typedef void null();
typedef null = void Function();
typedef void of();
typedef of = void Function();
typedef void on();
typedef on = void Function();
typedef void operator();
typedef operator = void Function();
typedef void out();
typedef out = void Function();
typedef void part();
typedef part = void Function();
typedef void patch();
typedef patch = void Function();
typedef void required();
typedef required = void Function();
typedef void rethrow();
typedef rethrow = void Function();
typedef void return();
typedef return = void Function();
typedef void set();
typedef set = void Function();
typedef void show();
typedef show = void Function();
typedef void source();
typedef source = void Function();
typedef void static();
typedef static = void Function();
typedef void super();
typedef super = void Function();
typedef void switch();
typedef switch = void Function();
typedef void sync();
typedef sync = void Function();
typedef void this();
typedef this = void Function();
typedef void throw();
typedef throw = void Function();
typedef void true();
typedef true = void Function();
typedef void try();
typedef try = void Function();
typedef void typedef();
typedef typedef = void Function();
typedef void var();
typedef var = void Function();
typedef void void();
typedef void = void Function();
typedef void while();
typedef while = void Function();
typedef void with();
typedef with = void Function();
typedef void yield();
typedef yield = void Function();
