successors.svg: successors.dot
	dot -Tsvg successors.dot -o successors.svg

predecessors.svg: predecessors.dot
	dot -Tsvg predecessors.dot -o predecessors.svg

dominators.svg: dominators.dot
	dot -Tsvg dominators.dot -o dominators.svg

owners.svg: owners.dot
	dot -Tsvg owners.dot -o owners.svg

all: successors.svg predecessors.svg dominators.svg owners.svg
