../ConsoleCollector.xpi: chrome.manifest install.rdf  chrome/content/console.js chrome/content/overlay.xul
	zip -r ../ConsoleCollector.xpi chrome.manifest install.rdf  chrome/content/console.js chrome/content/overlay.xul
