// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:developer';

import 'service_test_common.dart';
import 'test_helper.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart runtime/observatory/tests/service/local_variable_in_awaiter_async_frame_test.dart
//
const LINE_A = 21;
const LINE_B = 22;
// AUTOGENERATED END

Future<String> testFunction(String caption) async {
  await Future.delayed(Duration(milliseconds: 1)); // LINE_A
  return caption; // LINE_B
}

testMain() async {
  debugger();
  var str = await testFunction('The caption');
  print(str);
}

var tests = <IsolateTest>[
  hasStoppedAtBreakpoint,
  setBreakpointAtLine(LINE_A),
  setBreakpointAtLine(LINE_B),
  resumeIsolate,
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_A),
  hasLocalVarInTopStackFrame('caption', 'frames'),
  resumeIsolate,
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_B),
  hasLocalVarInTopStackFrame('caption', 'asyncCausalFrames'),
  hasLocalVarInTopStackFrame('caption', 'frames'),
  resumeIsolate,
];

main(args) => runIsolateTests(args, tests, testeeConcurrent: testMain);
