/**
 */

// Supplements and corrects errors in WebKit IDL to better align with browser
// neutral APIs.

module default {
  Node implements events::EventTarget;
  MessagePort implements events::EventTarget;
  EventSource implements events::EventTarget;
  Window implements events::EventTarget;
  ApplicationCache implements events::EventTarget;
  XMLHttpRequest implements events::EventTarget;
  XMLHttpRequestUpload implements events::EventTarget;
  Notification implements events::EventTarget;
  AbstractWorker implements events::EventTarget;
  WorkerContext implements events::EventTarget;
  SVGElementInstance implements events::EventTarget;
  WebSocket implements events::EventTarget;
}
