// Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
//
// This file has been automatically generated. Please do not edit it manually.
// To regenerate the file, use the script
// "pkg/analysis_server/tool/completion_metrics/relevance_table_generator.dart",
// passing it the location of a corpus of code that is large enough for the
// computed values to be statistically meaningful.

import 'package:analysis_server/src/services/completion/dart/probability_range.dart';
import 'package:analyzer_plugin/protocol/protocol_common.dart';

/// A table keyed by completion location and element kind whose values are the
/// ranges of the relevance of those element kinds in those locations.
const elementKindRelevance = {
  'Annotation_name': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.029),
    ElementKind.GETTER: ProbabilityRange(lower: 0.029, upper: 1.000),
  },
  'ArgumentList_annotation_named': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.979),
    ElementKind.CLASS: ProbabilityRange(lower: 0.979, upper: 0.984),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.984, upper: 1.000),
  },
  'ArgumentList_annotation_unnamed': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'ArgumentList_constructorRedirect_named': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.027),
    ElementKind.GETTER: ProbabilityRange(lower: 0.027, upper: 0.029),
    ElementKind.ENUM: ProbabilityRange(lower: 0.029, upper: 0.031),
    ElementKind.CLASS: ProbabilityRange(lower: 0.031, upper: 0.034),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.034, upper: 0.044),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.044, upper: 1.000),
  },
  'ArgumentList_constructorRedirect_unnamed': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.199),
    ElementKind.GETTER: ProbabilityRange(lower: 0.199, upper: 0.201),
    ElementKind.METHOD: ProbabilityRange(lower: 0.201, upper: 0.206),
    ElementKind.ENUM: ProbabilityRange(lower: 0.206, upper: 0.212),
    ElementKind.CLASS: ProbabilityRange(lower: 0.212, upper: 0.230),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.230, upper: 0.279),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.279, upper: 1.000),
  },
  'ArgumentList_constructor_named': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.485),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.485, upper: 0.487),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.487, upper: 0.489),
    ElementKind.ENUM: ProbabilityRange(lower: 0.489, upper: 0.501),
    ElementKind.GETTER: ProbabilityRange(lower: 0.501, upper: 0.539),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.539, upper: 0.579),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.579, upper: 0.646),
    ElementKind.CLASS: ProbabilityRange(lower: 0.646, upper: 0.735),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.735, upper: 1.000),
  },
  'ArgumentList_constructor_unnamed': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.617),
    ElementKind.METHOD: ProbabilityRange(lower: 0.617, upper: 0.621),
    ElementKind.ENUM: ProbabilityRange(lower: 0.621, upper: 0.629),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.629, upper: 0.645),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.645, upper: 0.683),
    ElementKind.GETTER: ProbabilityRange(lower: 0.683, upper: 0.733),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.733, upper: 0.811),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.811, upper: 0.905),
    ElementKind.CLASS: ProbabilityRange(lower: 0.905, upper: 1.000),
  },
  'ArgumentList_function_named': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.616),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.616, upper: 0.648),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.648, upper: 0.792),
    ElementKind.GETTER: ProbabilityRange(lower: 0.792, upper: 1.000),
  },
  'ArgumentList_function_unnamed': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.220),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.220, upper: 0.227),
    ElementKind.ENUM: ProbabilityRange(lower: 0.227, upper: 0.237),
    ElementKind.CLASS: ProbabilityRange(lower: 0.237, upper: 0.255),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.255, upper: 0.280),
    ElementKind.GETTER: ProbabilityRange(lower: 0.280, upper: 0.347),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.347, upper: 0.583),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.583, upper: 1.000),
  },
  'ArgumentList_method_named': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.548),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.548, upper: 0.551),
    ElementKind.METHOD: ProbabilityRange(lower: 0.551, upper: 0.555),
    ElementKind.ENUM: ProbabilityRange(lower: 0.555, upper: 0.568),
    ElementKind.CLASS: ProbabilityRange(lower: 0.568, upper: 0.626),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.626, upper: 0.686),
    ElementKind.GETTER: ProbabilityRange(lower: 0.686, upper: 0.764),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.764, upper: 0.854),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.854, upper: 1.000),
  },
  'ArgumentList_method_unnamed': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.387),
    ElementKind.SETTER: ProbabilityRange(lower: 0.387, upper: 0.387),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.387, upper: 0.387),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.387, upper: 0.388),
    ElementKind.ENUM: ProbabilityRange(lower: 0.388, upper: 0.394),
    ElementKind.METHOD: ProbabilityRange(lower: 0.394, upper: 0.402),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.402, upper: 0.425),
    ElementKind.CLASS: ProbabilityRange(lower: 0.425, upper: 0.452),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.452, upper: 0.510),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.510, upper: 0.624),
    ElementKind.GETTER: ProbabilityRange(lower: 0.624, upper: 0.746),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.746, upper: 1.000),
  },
  'ArgumentList_widgetConstructor_named': {
    ElementKind.SETTER: ProbabilityRange(lower: 0.000, upper: 0.351),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.351, upper: 0.352),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.352, upper: 0.355),
    ElementKind.METHOD: ProbabilityRange(lower: 0.355, upper: 0.368),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.368, upper: 0.387),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.387, upper: 0.422),
    ElementKind.ENUM: ProbabilityRange(lower: 0.422, upper: 0.482),
    ElementKind.GETTER: ProbabilityRange(lower: 0.482, upper: 0.552),
    ElementKind.CLASS: ProbabilityRange(lower: 0.552, upper: 0.636),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.636, upper: 1.000),
  },
  'ArgumentList_widgetConstructor_unnamed': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.461),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.461, upper: 0.463),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.463, upper: 0.469),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.469, upper: 0.475),
    ElementKind.METHOD: ProbabilityRange(lower: 0.475, upper: 0.491),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.491, upper: 0.541),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.541, upper: 0.612),
    ElementKind.GETTER: ProbabilityRange(lower: 0.612, upper: 0.757),
    ElementKind.CLASS: ProbabilityRange(lower: 0.757, upper: 1.000),
  },
  'AsExpression_type': {
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.000, upper: 0.000),
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.001),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.001, upper: 0.002),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.002, upper: 0.012),
    ElementKind.CLASS: ProbabilityRange(lower: 0.012, upper: 1.000),
  },
  'AssertInitializer_condition': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'AssertInitializer_message': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'AssertStatement_condition': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.142),
    ElementKind.METHOD: ProbabilityRange(lower: 0.142, upper: 0.176),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.176, upper: 0.226),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.226, upper: 0.332),
    ElementKind.GETTER: ProbabilityRange(lower: 0.332, upper: 0.662),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.662, upper: 1.000),
  },
  'AssertStatement_message': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'AssignmentExpression_rightHandSide': {
    ElementKind.SETTER: ProbabilityRange(lower: 0.000, upper: 0.305),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.305, upper: 0.306),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.306, upper: 0.318),
    ElementKind.METHOD: ProbabilityRange(lower: 0.318, upper: 0.329),
    ElementKind.ENUM: ProbabilityRange(lower: 0.329, upper: 0.350),
    ElementKind.CLASS: ProbabilityRange(lower: 0.350, upper: 0.395),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.395, upper: 0.490),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.490, upper: 0.601),
    ElementKind.GETTER: ProbabilityRange(lower: 0.601, upper: 0.740),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.740, upper: 1.000),
  },
  'AwaitExpression_expression': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.022),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.022, upper: 0.049),
    ElementKind.METHOD: ProbabilityRange(lower: 0.049, upper: 0.144),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.144, upper: 0.291),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.291, upper: 0.448),
    ElementKind.CLASS: ProbabilityRange(lower: 0.448, upper: 0.606),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.606, upper: 0.773),
    ElementKind.GETTER: ProbabilityRange(lower: 0.773, upper: 1.000),
  },
  'BinaryExpression_!=_rightOperand': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.874),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.874, upper: 0.874),
    ElementKind.METHOD: ProbabilityRange(lower: 0.874, upper: 0.875),
    ElementKind.CLASS: ProbabilityRange(lower: 0.875, upper: 0.886),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.886, upper: 0.903),
    ElementKind.ENUM: ProbabilityRange(lower: 0.903, upper: 0.921),
    ElementKind.GETTER: ProbabilityRange(lower: 0.921, upper: 0.958),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.958, upper: 1.000),
  },
  'BinaryExpression_%_rightOperand': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.719),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.719, upper: 0.725),
    ElementKind.CLASS: ProbabilityRange(lower: 0.725, upper: 0.752),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.752, upper: 0.784),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.784, upper: 0.853),
    ElementKind.GETTER: ProbabilityRange(lower: 0.853, upper: 1.000),
  },
  'BinaryExpression_&&_rightOperand': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.108),
    ElementKind.METHOD: ProbabilityRange(lower: 0.108, upper: 0.113),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.113, upper: 0.123),
    ElementKind.CLASS: ProbabilityRange(lower: 0.123, upper: 0.138),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.138, upper: 0.260),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.260, upper: 0.442),
    ElementKind.GETTER: ProbabilityRange(lower: 0.442, upper: 1.000),
  },
  'BinaryExpression_&_rightOperand': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 0.266),
    ElementKind.GETTER: ProbabilityRange(lower: 0.266, upper: 0.364),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.364, upper: 0.462),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.462, upper: 0.723),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.723, upper: 1.000),
  },
  'BinaryExpression_*_rightOperand': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.611),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.611, upper: 0.613),
    ElementKind.METHOD: ProbabilityRange(lower: 0.613, upper: 0.616),
    ElementKind.CLASS: ProbabilityRange(lower: 0.616, upper: 0.625),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.625, upper: 0.640),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.640, upper: 0.663),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.663, upper: 0.714),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.714, upper: 0.850),
    ElementKind.GETTER: ProbabilityRange(lower: 0.850, upper: 1.000),
  },
  'BinaryExpression_+_rightOperand': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.500),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.500, upper: 0.505),
    ElementKind.METHOD: ProbabilityRange(lower: 0.505, upper: 0.511),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.511, upper: 0.526),
    ElementKind.CLASS: ProbabilityRange(lower: 0.526, upper: 0.549),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.549, upper: 0.668),
    ElementKind.GETTER: ProbabilityRange(lower: 0.668, upper: 0.825),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.825, upper: 1.000),
  },
  'BinaryExpression_-_rightOperand': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.473),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.473, upper: 0.477),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.477, upper: 0.483),
    ElementKind.METHOD: ProbabilityRange(lower: 0.483, upper: 0.491),
    ElementKind.CLASS: ProbabilityRange(lower: 0.491, upper: 0.506),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.506, upper: 0.597),
    ElementKind.GETTER: ProbabilityRange(lower: 0.597, upper: 0.793),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.793, upper: 1.000),
  },
  'BinaryExpression_/_rightOperand': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.762),
    ElementKind.METHOD: ProbabilityRange(lower: 0.762, upper: 0.763),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.763, upper: 0.765),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.765, upper: 0.771),
    ElementKind.CLASS: ProbabilityRange(lower: 0.771, upper: 0.779),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.779, upper: 0.818),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.818, upper: 0.907),
    ElementKind.GETTER: ProbabilityRange(lower: 0.907, upper: 1.000),
  },
  'BinaryExpression_<<_rightOperand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.756),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.756, upper: 0.854),
    ElementKind.GETTER: ProbabilityRange(lower: 0.854, upper: 1.000),
  },
  'BinaryExpression_<=_rightOperand': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 0.607),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.607, upper: 0.717),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.717, upper: 0.848),
    ElementKind.GETTER: ProbabilityRange(lower: 0.848, upper: 1.000),
  },
  'BinaryExpression_<_rightOperand': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.424),
    ElementKind.METHOD: ProbabilityRange(lower: 0.424, upper: 0.425),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.425, upper: 0.426),
    ElementKind.CLASS: ProbabilityRange(lower: 0.426, upper: 0.438),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.438, upper: 0.557),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.557, upper: 0.773),
    ElementKind.GETTER: ProbabilityRange(lower: 0.773, upper: 1.000),
  },
  'BinaryExpression_==_rightOperand': {
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.000, upper: 0.567),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.567, upper: 0.567),
    ElementKind.METHOD: ProbabilityRange(lower: 0.567, upper: 0.567),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.567, upper: 0.567),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.567, upper: 0.568),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.568, upper: 0.591),
    ElementKind.CLASS: ProbabilityRange(lower: 0.591, upper: 0.629),
    ElementKind.GETTER: ProbabilityRange(lower: 0.629, upper: 0.679),
    ElementKind.ENUM: ProbabilityRange(lower: 0.679, upper: 0.807),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.807, upper: 1.000),
  },
  'BinaryExpression_>=_rightOperand': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.714),
    ElementKind.CLASS: ProbabilityRange(lower: 0.714, upper: 0.731),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.731, upper: 0.791),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.791, upper: 0.854),
    ElementKind.GETTER: ProbabilityRange(lower: 0.854, upper: 1.000),
  },
  'BinaryExpression_>>_rightOperand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'BinaryExpression_>_rightOperand': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.813),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.813, upper: 0.814),
    ElementKind.ENUM: ProbabilityRange(lower: 0.814, upper: 0.815),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.815, upper: 0.818),
    ElementKind.CLASS: ProbabilityRange(lower: 0.818, upper: 0.826),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.826, upper: 0.867),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.867, upper: 0.928),
    ElementKind.GETTER: ProbabilityRange(lower: 0.928, upper: 1.000),
  },
  'BinaryExpression_??_rightOperand': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.665),
    ElementKind.METHOD: ProbabilityRange(lower: 0.665, upper: 0.668),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.668, upper: 0.673),
    ElementKind.ENUM: ProbabilityRange(lower: 0.673, upper: 0.684),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.684, upper: 0.726),
    ElementKind.GETTER: ProbabilityRange(lower: 0.726, upper: 0.768),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.768, upper: 0.816),
    ElementKind.CLASS: ProbabilityRange(lower: 0.816, upper: 0.871),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.871, upper: 1.000),
  },
  'BinaryExpression_^_rightOperand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.118),
    ElementKind.GETTER: ProbabilityRange(lower: 0.118, upper: 1.000),
  },
  'BinaryExpression_|_rightOperand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.143),
    ElementKind.GETTER: ProbabilityRange(lower: 0.143, upper: 0.429),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.429, upper: 1.000),
  },
  'BinaryExpression_||_rightOperand': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.144),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.144, upper: 0.148),
    ElementKind.CLASS: ProbabilityRange(lower: 0.148, upper: 0.168),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.168, upper: 0.378),
    ElementKind.GETTER: ProbabilityRange(lower: 0.378, upper: 0.663),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.663, upper: 1.000),
  },
  'BinaryExpression_~/_rightOperand': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 0.627),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.627, upper: 0.640),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.640, upper: 0.677),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.677, upper: 0.795),
    ElementKind.GETTER: ProbabilityRange(lower: 0.795, upper: 1.000),
  },
  'Block_statement': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.537),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.537, upper: 0.537),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.537, upper: 0.538),
    ElementKind.ENUM: ProbabilityRange(lower: 0.538, upper: 0.538),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.538, upper: 0.539),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.539, upper: 0.540),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.540, upper: 0.563),
    ElementKind.METHOD: ProbabilityRange(lower: 0.563, upper: 0.614),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.614, upper: 0.674),
    ElementKind.GETTER: ProbabilityRange(lower: 0.674, upper: 0.743),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.743, upper: 0.825),
    ElementKind.SETTER: ProbabilityRange(lower: 0.825, upper: 0.911),
    ElementKind.CLASS: ProbabilityRange(lower: 0.911, upper: 1.000),
  },
  'CatchClause_exceptionType': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'ClassDeclaration_member': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.390),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.390, upper: 0.390),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.390, upper: 0.391),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.391, upper: 0.392),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.392, upper: 0.393),
    ElementKind.ENUM: ProbabilityRange(lower: 0.393, upper: 0.399),
    ElementKind.CLASS: ProbabilityRange(lower: 0.399, upper: 1.000),
  },
  'ClassTypeAlias_superclass': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'CommentReference_identifier': {
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.000, upper: 0.001),
    ElementKind.SETTER: ProbabilityRange(lower: 0.001, upper: 0.001),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.001, upper: 0.002),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.002, upper: 0.004),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.004, upper: 0.008),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.008, upper: 0.021),
    ElementKind.METHOD: ProbabilityRange(lower: 0.021, upper: 0.054),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.054, upper: 0.106),
    ElementKind.ENUM: ProbabilityRange(lower: 0.106, upper: 0.167),
    ElementKind.GETTER: ProbabilityRange(lower: 0.167, upper: 0.425),
    ElementKind.CLASS: ProbabilityRange(lower: 0.425, upper: 1.000),
  },
  'CompilationUnit_declaration': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.820),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.820, upper: 0.820),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.820, upper: 0.821),
    ElementKind.ENUM: ProbabilityRange(lower: 0.821, upper: 0.823),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.823, upper: 0.837),
    ElementKind.CLASS: ProbabilityRange(lower: 0.837, upper: 1.000),
  },
  'ConditionalExpression_elseExpression': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.370),
    ElementKind.SETTER: ProbabilityRange(lower: 0.370, upper: 0.375),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.375, upper: 0.383),
    ElementKind.METHOD: ProbabilityRange(lower: 0.383, upper: 0.403),
    ElementKind.ENUM: ProbabilityRange(lower: 0.403, upper: 0.427),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.427, upper: 0.482),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.482, upper: 0.549),
    ElementKind.GETTER: ProbabilityRange(lower: 0.549, upper: 0.655),
    ElementKind.CLASS: ProbabilityRange(lower: 0.655, upper: 0.790),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.790, upper: 1.000),
  },
  'ConditionalExpression_thenExpression': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.390),
    ElementKind.SETTER: ProbabilityRange(lower: 0.390, upper: 0.395),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.395, upper: 0.402),
    ElementKind.METHOD: ProbabilityRange(lower: 0.402, upper: 0.424),
    ElementKind.ENUM: ProbabilityRange(lower: 0.424, upper: 0.450),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.450, upper: 0.500),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.500, upper: 0.556),
    ElementKind.GETTER: ProbabilityRange(lower: 0.556, upper: 0.634),
    ElementKind.CLASS: ProbabilityRange(lower: 0.634, upper: 0.777),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.777, upper: 1.000),
  },
  'ConstructorDeclaration_initializer': {
    ElementKind.FIELD: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'ConstructorDeclaration_returnType': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'ConstructorFieldInitializer_expression': {
    ElementKind.GETTER: ProbabilityRange(lower: 0.000, upper: 0.183),
    ElementKind.METHOD: ProbabilityRange(lower: 0.183, upper: 0.187),
    ElementKind.ENUM: ProbabilityRange(lower: 0.187, upper: 0.195),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.195, upper: 0.220),
    ElementKind.CLASS: ProbabilityRange(lower: 0.220, upper: 0.272),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.272, upper: 0.396),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.396, upper: 1.000),
  },
  'DefaultFormalParameter_defaultValue': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.716),
    ElementKind.METHOD: ProbabilityRange(lower: 0.716, upper: 0.716),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.716, upper: 0.717),
    ElementKind.GETTER: ProbabilityRange(lower: 0.717, upper: 0.733),
    ElementKind.ENUM: ProbabilityRange(lower: 0.733, upper: 0.776),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.776, upper: 0.838),
    ElementKind.CLASS: ProbabilityRange(lower: 0.838, upper: 1.000),
  },
  'DoStatement_condition': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.333),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.333, upper: 1.000),
  },
  'Expression': {
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.000, upper: 0.386),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.386, upper: 0.386),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.386, upper: 0.386),
    ElementKind.TOP_LEVEL_VARIABLE:
        ProbabilityRange(lower: 0.386, upper: 0.386),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.386, upper: 0.386),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.386, upper: 0.388),
    ElementKind.SETTER: ProbabilityRange(lower: 0.388, upper: 0.402),
    ElementKind.ENUM: ProbabilityRange(lower: 0.402, upper: 0.418),
    ElementKind.METHOD: ProbabilityRange(lower: 0.418, upper: 0.434),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.434, upper: 0.450),
    ElementKind.CLASS: ProbabilityRange(lower: 0.450, upper: 0.522),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.522, upper: 0.607),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.607, upper: 0.701),
    ElementKind.GETTER: ProbabilityRange(lower: 0.701, upper: 0.839),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.839, upper: 1.000),
  },
  'ExpressionFunctionBody_expression': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.352),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.352, upper: 0.352),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.352, upper: 0.358),
    ElementKind.ENUM: ProbabilityRange(lower: 0.358, upper: 0.363),
    ElementKind.SETTER: ProbabilityRange(lower: 0.363, upper: 0.373),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.373, upper: 0.394),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.394, upper: 0.419),
    ElementKind.CLASS: ProbabilityRange(lower: 0.419, upper: 0.452),
    ElementKind.METHOD: ProbabilityRange(lower: 0.452, upper: 0.487),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.487, upper: 0.613),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.613, upper: 0.794),
    ElementKind.GETTER: ProbabilityRange(lower: 0.794, upper: 1.000),
  },
  'ExpressionStatement_expression': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.132),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.132, upper: 0.134),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.134, upper: 0.136),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.136, upper: 0.139),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.139, upper: 0.190),
    ElementKind.CLASS: ProbabilityRange(lower: 0.190, upper: 0.255),
    ElementKind.METHOD: ProbabilityRange(lower: 0.255, upper: 0.361),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.361, upper: 0.482),
    ElementKind.GETTER: ProbabilityRange(lower: 0.482, upper: 0.625),
    ElementKind.SETTER: ProbabilityRange(lower: 0.625, upper: 0.801),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.801, upper: 1.000),
  },
  'ExtendsClause_superclass': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.000),
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'ExtensionDeclaration_extendedType': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.053),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.053, upper: 0.105),
    ElementKind.CLASS: ProbabilityRange(lower: 0.105, upper: 1.000),
  },
  'ExtensionDeclaration_member': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.120),
    ElementKind.CLASS: ProbabilityRange(lower: 0.120, upper: 1.000),
  },
  'ForEachPartsWithDeclaration_iterable': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.016),
    ElementKind.ENUM: ProbabilityRange(lower: 0.016, upper: 0.018),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.018, upper: 0.022),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.022, upper: 0.029),
    ElementKind.CLASS: ProbabilityRange(lower: 0.029, upper: 0.036),
    ElementKind.GETTER: ProbabilityRange(lower: 0.036, upper: 0.288),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.288, upper: 0.607),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.607, upper: 1.000),
  },
  'ForEachPartsWithDeclaration_loopVariable': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.703),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.703, upper: 0.704),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.704, upper: 0.706),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.706, upper: 0.708),
    ElementKind.ENUM: ProbabilityRange(lower: 0.708, upper: 0.712),
    ElementKind.CLASS: ProbabilityRange(lower: 0.712, upper: 1.000),
  },
  'ForElement_body': {
    ElementKind.GETTER: ProbabilityRange(lower: 0.000, upper: 0.900),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.900, upper: 0.904),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.904, upper: 0.908),
    ElementKind.METHOD: ProbabilityRange(lower: 0.908, upper: 0.918),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.918, upper: 0.937),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.937, upper: 1.000),
  },
  'ForParts_condition': {
    ElementKind.GETTER: ProbabilityRange(lower: 0.000, upper: 0.023),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.023, upper: 1.000),
  },
  'ForParts_updater': {
    ElementKind.SETTER: ProbabilityRange(lower: 0.000, upper: 0.067),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.067, upper: 1.000),
  },
  'FormalParameterList_parameter': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.245),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.245, upper: 0.247),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.247, upper: 0.255),
    ElementKind.ENUM: ProbabilityRange(lower: 0.255, upper: 0.267),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.267, upper: 0.284),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.284, upper: 0.311),
    ElementKind.CLASS: ProbabilityRange(lower: 0.311, upper: 1.000),
  },
  'GenericTypeAlias_functionType': {
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.000, upper: 0.590),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.590, upper: 0.610),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.610, upper: 0.660),
    ElementKind.CLASS: ProbabilityRange(lower: 0.660, upper: 1.000),
  },
  'HideCombinator_hiddenName': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.059),
    ElementKind.CLASS: ProbabilityRange(lower: 0.059, upper: 1.000),
  },
  'IfElement_condition': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.157),
    ElementKind.CLASS: ProbabilityRange(lower: 0.157, upper: 0.172),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.172, upper: 0.338),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.338, upper: 0.633),
    ElementKind.GETTER: ProbabilityRange(lower: 0.633, upper: 1.000),
  },
  'IfElement_elseElement': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.333),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.333, upper: 1.000),
  },
  'IfElement_thenElement': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.212),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.212, upper: 0.219),
    ElementKind.CLASS: ProbabilityRange(lower: 0.219, upper: 0.228),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.228, upper: 0.239),
    ElementKind.GETTER: ProbabilityRange(lower: 0.239, upper: 0.254),
    ElementKind.METHOD: ProbabilityRange(lower: 0.254, upper: 0.281),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.281, upper: 1.000),
  },
  'IfStatement_condition': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.117),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.117, upper: 0.118),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.118, upper: 0.118),
    ElementKind.ENUM: ProbabilityRange(lower: 0.118, upper: 0.118),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.118, upper: 0.119),
    ElementKind.METHOD: ProbabilityRange(lower: 0.119, upper: 0.129),
    ElementKind.CLASS: ProbabilityRange(lower: 0.129, upper: 0.145),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.145, upper: 0.167),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.167, upper: 0.388),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.388, upper: 0.688),
    ElementKind.GETTER: ProbabilityRange(lower: 0.688, upper: 1.000),
  },
  'IfStatement_else': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.968),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.968, upper: 0.969),
    ElementKind.SETTER: ProbabilityRange(lower: 0.969, upper: 0.972),
    ElementKind.CLASS: ProbabilityRange(lower: 0.972, upper: 0.976),
    ElementKind.GETTER: ProbabilityRange(lower: 0.976, upper: 0.981),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.981, upper: 0.990),
    ElementKind.METHOD: ProbabilityRange(lower: 0.990, upper: 1.000),
  },
  'IfStatement_then': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.934),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.934, upper: 0.935),
    ElementKind.CLASS: ProbabilityRange(lower: 0.935, upper: 0.937),
    ElementKind.SETTER: ProbabilityRange(lower: 0.937, upper: 0.942),
    ElementKind.METHOD: ProbabilityRange(lower: 0.942, upper: 0.952),
    ElementKind.GETTER: ProbabilityRange(lower: 0.952, upper: 0.964),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.964, upper: 0.981),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.981, upper: 1.000),
  },
  'ImplementsClause_interface': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.003),
    ElementKind.CLASS: ProbabilityRange(lower: 0.003, upper: 1.000),
  },
  'IndexExpression_index': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.655),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.655, upper: 0.655),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.655, upper: 0.656),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.656, upper: 0.656),
    ElementKind.METHOD: ProbabilityRange(lower: 0.656, upper: 0.657),
    ElementKind.ENUM: ProbabilityRange(lower: 0.657, upper: 0.659),
    ElementKind.CLASS: ProbabilityRange(lower: 0.659, upper: 0.664),
    ElementKind.GETTER: ProbabilityRange(lower: 0.664, upper: 0.760),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.760, upper: 0.863),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.863, upper: 1.000),
  },
  'InterpolationExpression_expression': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.035),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.035, upper: 0.035),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.035, upper: 0.036),
    ElementKind.ENUM: ProbabilityRange(lower: 0.036, upper: 0.036),
    ElementKind.METHOD: ProbabilityRange(lower: 0.036, upper: 0.044),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.044, upper: 0.074),
    ElementKind.CLASS: ProbabilityRange(lower: 0.074, upper: 0.198),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.198, upper: 0.388),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.388, upper: 0.633),
    ElementKind.GETTER: ProbabilityRange(lower: 0.633, upper: 1.000),
  },
  'IsExpression_type': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.002),
    ElementKind.ENUM: ProbabilityRange(lower: 0.002, upper: 0.005),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.005, upper: 0.008),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.008, upper: 0.013),
    ElementKind.CLASS: ProbabilityRange(lower: 0.013, upper: 1.000),
  },
  'ListLiteral_element': {
    ElementKind.SETTER: ProbabilityRange(lower: 0.000, upper: 0.324),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.324, upper: 0.325),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.325, upper: 0.327),
    ElementKind.ENUM: ProbabilityRange(lower: 0.327, upper: 0.331),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.331, upper: 0.338),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.338, upper: 0.349),
    ElementKind.GETTER: ProbabilityRange(lower: 0.349, upper: 0.362),
    ElementKind.METHOD: ProbabilityRange(lower: 0.362, upper: 0.379),
    ElementKind.CLASS: ProbabilityRange(lower: 0.379, upper: 0.407),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.407, upper: 1.000),
  },
  'MapLiteralEntry_value': {
    ElementKind.PREFIX: ProbabilityRange(lower: 0.000, upper: 0.814),
    ElementKind.METHOD: ProbabilityRange(lower: 0.814, upper: 0.814),
    ElementKind.ENUM: ProbabilityRange(lower: 0.814, upper: 0.816),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.816, upper: 0.818),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.818, upper: 0.823),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.823, upper: 0.829),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.829, upper: 0.849),
    ElementKind.GETTER: ProbabilityRange(lower: 0.849, upper: 0.884),
    ElementKind.CLASS: ProbabilityRange(lower: 0.884, upper: 1.000),
  },
  'MixinDeclaration_member': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.116),
    ElementKind.ENUM: ProbabilityRange(lower: 0.116, upper: 0.121),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.121, upper: 0.128),
    ElementKind.CLASS: ProbabilityRange(lower: 0.128, upper: 1.000),
  },
  'OnClause_superclassConstraint': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.392),
    ElementKind.CLASS: ProbabilityRange(lower: 0.392, upper: 1.000),
  },
  'ParenthesizedExpression_expression': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.217),
    ElementKind.ENUM: ProbabilityRange(lower: 0.217, upper: 0.218),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.218, upper: 0.220),
    ElementKind.SETTER: ProbabilityRange(lower: 0.220, upper: 0.223),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.223, upper: 0.225),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.225, upper: 0.230),
    ElementKind.CLASS: ProbabilityRange(lower: 0.230, upper: 0.276),
    ElementKind.METHOD: ProbabilityRange(lower: 0.276, upper: 0.333),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.333, upper: 0.516),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.516, upper: 0.730),
    ElementKind.GETTER: ProbabilityRange(lower: 0.730, upper: 1.000),
  },
  'PrefixExpression_!_operand': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.063),
    ElementKind.METHOD: ProbabilityRange(lower: 0.063, upper: 0.094),
    ElementKind.CLASS: ProbabilityRange(lower: 0.094, upper: 0.142),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.142, upper: 0.330),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.330, upper: 0.584),
    ElementKind.GETTER: ProbabilityRange(lower: 0.584, upper: 1.000),
  },
  'PrefixExpression_++_operand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.035),
    ElementKind.GETTER: ProbabilityRange(lower: 0.035, upper: 0.123),
    ElementKind.SETTER: ProbabilityRange(lower: 0.123, upper: 0.351),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.351, upper: 1.000),
  },
  'PrefixExpression_--_operand': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.063),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.063, upper: 0.313),
    ElementKind.SETTER: ProbabilityRange(lower: 0.313, upper: 0.625),
    ElementKind.GETTER: ProbabilityRange(lower: 0.625, upper: 1.000),
  },
  'PrefixExpression_-_operand': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.810),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.810, upper: 0.813),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.813, upper: 0.820),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.820, upper: 0.841),
    ElementKind.CLASS: ProbabilityRange(lower: 0.841, upper: 0.866),
    ElementKind.GETTER: ProbabilityRange(lower: 0.866, upper: 0.925),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.925, upper: 1.000),
  },
  'PrefixExpression_~_operand': {
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.000, upper: 1.000),
  },
  'PropertyAccess_propertyName': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.002),
    ElementKind.SETTER: ProbabilityRange(lower: 0.002, upper: 0.104),
    ElementKind.GETTER: ProbabilityRange(lower: 0.104, upper: 1.000),
  },
  'ReturnStatement_expression': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.242),
    ElementKind.SETTER: ProbabilityRange(lower: 0.242, upper: 0.242),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.242, upper: 0.245),
    ElementKind.ENUM: ProbabilityRange(lower: 0.245, upper: 0.252),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.252, upper: 0.269),
    ElementKind.METHOD: ProbabilityRange(lower: 0.269, upper: 0.294),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.294, upper: 0.346),
    ElementKind.GETTER: ProbabilityRange(lower: 0.346, upper: 0.403),
    ElementKind.CLASS: ProbabilityRange(lower: 0.403, upper: 0.464),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.464, upper: 0.561),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.561, upper: 1.000),
  },
  'SetOrMapLiteral_element': {
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.000, upper: 0.974),
    ElementKind.METHOD: ProbabilityRange(lower: 0.974, upper: 0.974),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.974, upper: 0.974),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.974, upper: 0.974),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.974, upper: 0.974),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.974, upper: 0.978),
    ElementKind.ENUM: ProbabilityRange(lower: 0.978, upper: 0.983),
    ElementKind.GETTER: ProbabilityRange(lower: 0.983, upper: 0.991),
    ElementKind.CLASS: ProbabilityRange(lower: 0.991, upper: 1.000),
  },
  'ShowCombinator_shownName': {
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.000, upper: 0.005),
    ElementKind.ENUM: ProbabilityRange(lower: 0.005, upper: 0.032),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.032, upper: 0.212),
    ElementKind.TOP_LEVEL_VARIABLE:
        ProbabilityRange(lower: 0.212, upper: 0.561),
    ElementKind.CLASS: ProbabilityRange(lower: 0.561, upper: 1.000),
  },
  'SpreadElement_expression': {
    ElementKind.ENUM: ProbabilityRange(lower: 0.000, upper: 0.332),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.332, upper: 0.347),
    ElementKind.CLASS: ProbabilityRange(lower: 0.347, upper: 0.376),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.376, upper: 0.443),
    ElementKind.METHOD: ProbabilityRange(lower: 0.443, upper: 0.531),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.531, upper: 0.631),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.631, upper: 0.734),
    ElementKind.GETTER: ProbabilityRange(lower: 0.734, upper: 1.000),
  },
  'Statement': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.600),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.600, upper: 0.600),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.600, upper: 0.600),
    ElementKind.ENUM: ProbabilityRange(lower: 0.600, upper: 0.601),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.601, upper: 0.601),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.601, upper: 0.603),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.603, upper: 0.623),
    ElementKind.METHOD: ProbabilityRange(lower: 0.623, upper: 0.666),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.666, upper: 0.716),
    ElementKind.GETTER: ProbabilityRange(lower: 0.716, upper: 0.774),
    ElementKind.SETTER: ProbabilityRange(lower: 0.774, upper: 0.846),
    ElementKind.CLASS: ProbabilityRange(lower: 0.846, upper: 0.919),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.919, upper: 1.000),
  },
  'SwitchCase_expression': {
    ElementKind.GETTER: ProbabilityRange(lower: 0.000, upper: 0.541),
    ElementKind.CLASS: ProbabilityRange(lower: 0.541, upper: 0.677),
    ElementKind.ENUM: ProbabilityRange(lower: 0.677, upper: 1.000),
  },
  'SwitchMember_statement': {
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.000, upper: 0.691),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.691, upper: 0.691),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.691, upper: 0.697),
    ElementKind.CLASS: ProbabilityRange(lower: 0.697, upper: 0.708),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.708, upper: 0.719),
    ElementKind.SETTER: ProbabilityRange(lower: 0.719, upper: 0.733),
    ElementKind.METHOD: ProbabilityRange(lower: 0.733, upper: 0.748),
    ElementKind.GETTER: ProbabilityRange(lower: 0.748, upper: 0.765),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.765, upper: 1.000),
  },
  'SwitchStatement_expression': {
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.009),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.009, upper: 0.011),
    ElementKind.METHOD: ProbabilityRange(lower: 0.011, upper: 0.015),
    ElementKind.CLASS: ProbabilityRange(lower: 0.015, upper: 0.030),
    ElementKind.GETTER: ProbabilityRange(lower: 0.030, upper: 0.211),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.211, upper: 0.504),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.504, upper: 1.000),
  },
  'ThrowExpression_expression': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.833),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.833, upper: 0.834),
    ElementKind.CLASS: ProbabilityRange(lower: 0.834, upper: 0.836),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.836, upper: 1.000),
  },
  'TypeArgumentList_argument': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.021),
    ElementKind.FUNCTION_TYPE_ALIAS:
        ProbabilityRange(lower: 0.021, upper: 0.024),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.024, upper: 0.031),
    ElementKind.ENUM: ProbabilityRange(lower: 0.031, upper: 0.039),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.039, upper: 0.053),
    ElementKind.UNKNOWN: ProbabilityRange(lower: 0.053, upper: 0.163),
    ElementKind.CLASS: ProbabilityRange(lower: 0.163, upper: 1.000),
  },
  'TypeParameter_bound': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.016),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.016, upper: 0.039),
    ElementKind.CLASS: ProbabilityRange(lower: 0.039, upper: 1.000),
  },
  'VariableDeclaration_initializer': {
    ElementKind.MIXIN: ProbabilityRange(lower: 0.000, upper: 0.452),
    ElementKind.TYPE_PARAMETER: ProbabilityRange(lower: 0.452, upper: 0.452),
    ElementKind.PREFIX: ProbabilityRange(lower: 0.452, upper: 0.456),
    ElementKind.ENUM: ProbabilityRange(lower: 0.456, upper: 0.460),
    ElementKind.METHOD: ProbabilityRange(lower: 0.460, upper: 0.472),
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.472, upper: 0.497),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.497, upper: 0.561),
    ElementKind.CLASS: ProbabilityRange(lower: 0.561, upper: 0.630),
    ElementKind.GETTER: ProbabilityRange(lower: 0.630, upper: 0.712),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.712, upper: 0.794),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.794, upper: 1.000),
  },
  'WhileStatement_body': {
    ElementKind.METHOD: ProbabilityRange(lower: 0.000, upper: 0.985),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.985, upper: 1.000),
  },
  'WhileStatement_condition': {
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.000, upper: 0.083),
    ElementKind.GETTER: ProbabilityRange(lower: 0.083, upper: 0.109),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.109, upper: 1.000),
  },
  'WithClause_mixinType': {
    ElementKind.CLASS: ProbabilityRange(lower: 0.000, upper: 0.280),
    ElementKind.MIXIN: ProbabilityRange(lower: 0.280, upper: 1.000),
  },
  'YieldStatement_expression': {
    ElementKind.FUNCTION: ProbabilityRange(lower: 0.000, upper: 0.065),
    ElementKind.GETTER: ProbabilityRange(lower: 0.065, upper: 0.086),
    ElementKind.PARAMETER: ProbabilityRange(lower: 0.086, upper: 0.122),
    ElementKind.LOCAL_VARIABLE: ProbabilityRange(lower: 0.122, upper: 0.161),
    ElementKind.METHOD: ProbabilityRange(lower: 0.161, upper: 0.309),
    ElementKind.CONSTRUCTOR: ProbabilityRange(lower: 0.309, upper: 1.000),
  },
};
