(module $module0
  (type $#Top <...>)
  (type $Array<Object?> <...>)
  (type $Array<_Type> <...>)
  (type $JSExternWrapper <...>)
  (type $_FunctionType <...>)
  (table $cross-module-funcs-0 (export "cross-module-funcs-0") 11 funcref)
  (elem $cross-module-funcs-0
    (set 2 (ref.func $"_hashSeed implicit getter"))
    (set 3 (ref.func $SystemHash.combine))
    (set 4 (ref.func $_TypeUniverse.substituteFunctionTypeArgument))
    (set 5 (ref.func $print))
    (set 6 (ref.func $JSStringImpl._interpolate))
    (set 7 (ref.func $checkLibraryIsLoadedFromLoadId)))
  (func $_hashSeed implicit getter (result i64) <...>)
  (func $JSStringImpl._interpolate (param $var0 (ref $Array<Object?>)) (result (ref $JSExternWrapper)) <...>)
  (func $SystemHash.combine (param $var0 i64) (param $var1 i64) (result i64) <...>)
  (func $_TypeUniverse.substituteFunctionTypeArgument (param $var0 (ref $_FunctionType)) (param $var1 (ref $Array<_Type>)) (result (ref $_FunctionType)) <...>)
  (func $checkLibraryIsLoadedFromLoadId (param $var0 i64) (result i32) <...>)
  (func $print (param $var0 (ref null $#Top)) (result (ref null $#Top)) <...>)
)