(module $module0
  (type $#Top (struct
    (field $field0 i32)))
  (type $Array<Object?> (array (field (mut (ref null $#Top)))))
  (type $JSExternWrapper (sub $Object (struct
    (field $field0 i32)
    (field $field1 (mut i32))
    (field $_externRef externref))))
  (type $Object (sub $#Top (struct
    (field $field0 i32)
    (field $field1 (mut i32)))))
  (func $"wasm:js-string.charCodeAt (import)" (import "wasm:js-string" "charCodeAt") (param externref i32) (result i32))
  (@binaryen.removable.if.unused)
  (func $"wasm:js-string.equals (import)" (import "wasm:js-string" "equals") (param externref externref) (result i32))
  (@binaryen.removable.if.unused)
  (func $"wasm:js-string.length (import)" (import "wasm:js-string" "length") (param externref) (result i32))
  (table $cross-module-funcs-0 (export "cross-module-funcs-0") 17 funcref)
  (elem $cross-module-funcs-0
    (set 2 (ref.func $checkLibraryIsLoadedFromLoadId))
    (set 4 (ref.func $"Error._throwWithCurrentStackTrace <noInline>"))
    (set 5 (ref.func $"wasm:js-string.length (import)"))
    (set 6 (ref.func $"wasm:js-string.charCodeAt (import)"))
    (set 7 (ref.func $IntegerDivisionByZeroException))
    (set 8 (ref.func $JSStringImpl._interpolate3))
    (set 9 (ref.func $"wasm:js-string.equals (import)"))
    (set 10 (ref.func $JSStringImpl.substring))
    (set 11 (ref.func $JSStringImpl.+))
    (set 12 (ref.func $"_throwIndexError <noInline>"))
    (set 13 (ref.func $JSStringImpl._interpolate))
    (set 14 (ref.func $JSStringImpl.fromRefUnchecked))
    (set 15 (ref.func $JSStringImpl._interpolate2)))
  (func $Error._throwWithCurrentStackTrace <noInline> (param $var0 (ref $#Top)) (result (ref none)) <...>)
  (func $_throwIndexError <noInline> (param $var0 i64) (param $var1 i64) (param $var2 (ref null $JSExternWrapper)) (result (ref none)) <...>)
  (func $IntegerDivisionByZeroException (result (ref $Object)) <...>)
  (func $JSStringImpl.+ (param $var0 (ref $JSExternWrapper)) (param $var1 (ref $JSExternWrapper)) (result (ref $JSExternWrapper)) <...>)
  (func $JSStringImpl._interpolate (param $var0 (ref $Array<Object?>)) (result (ref $JSExternWrapper)) <...>)
  (func $JSStringImpl._interpolate2 (param $var0 (ref null $#Top)) (param $var1 (ref null $#Top)) (result (ref $JSExternWrapper)) <...>)
  (func $JSStringImpl._interpolate3 (param $var0 (ref null $#Top)) (param $var1 (ref null $#Top)) (param $var2 (ref null $#Top)) (result (ref $JSExternWrapper)) <...>)
  (func $JSStringImpl.fromRefUnchecked (param $var0 externref) (result (ref $JSExternWrapper)) <...>)
  (func $JSStringImpl.substring (param $var0 (ref $JSExternWrapper)) (param $var1 i64) (param $var2 i64) (result (ref $JSExternWrapper)) <...>)
  (func $checkLibraryIsLoadedFromLoadId (param $var0 i64) (result i32) <...>)
)