(module $module0
  (rec
    (type $#Closure-0-0 <...>)
    (type $type0 <...>)
    (type $#Vtable-0-0 <...>)
  )
  (type $#Closure-0-2 (sub final $#Closure-0-0 (struct
    (field $field0 i32)
    (field $field1 (mut i32))
    (field $context (ref struct))
    (field $vtable (ref $#Vtable-0-2))
    (field $functionType (ref $_FunctionType)))))
  (type $#DummyStruct <...>)
  (type $#Top <...>)
  (type $#Vtable-0-2 (sub final $#Vtable-0-0 (struct
    (field $dynamicClosureCallEntry (ref $type0))
    (field $closureCallEntry-0-2 (ref $type2)))))
  (type $Array<Object?> <...>)
  (type $Array<_NamedParameter> <...>)
  (type $Array<_Type> <...>)
  (type $_FunctionType <...>)
  (type $_InterfaceType <...>)
  (type $_TopType <...>)
  (type $type2 <...>)
  (global $"WasmArray<_NamedParameter>[0]" (ref $Array<_NamedParameter>) <...>)
  (global $"WasmArray<_Type>[0]" (ref $Array<_Type>) <...>)
  (global $"bar tear-off" (ref $#Closure-0-2)
    (i32.const 32)
    (i32.const 0)
    (global.get $global0)
    (ref.func $"bar tear-off dynamic call entry")
    (ref.func $"bar tear-off trampoline_334")
    (struct.new $#Vtable-0-2)
    (i32.const 12)
    (i32.const 0)
    (i32.const 0)
    (global.get $"WasmArray<_Type>[0]")
    (global.get $"WasmArray<_Type>[0]")
    (global.get $_TopType_354)
    (global.get $_InterfaceType_30)
    (global.get $_InterfaceType_360)
    (array.new_fixed $Array<_Type> 2)
    (i64.const 1)
    (global.get $"WasmArray<_NamedParameter>[0]")
    (struct.new $_FunctionType)
    (struct.new $#Closure-0-2))
  (global $"foo tear-off" (ref $#Closure-0-2)
    (i32.const 32)
    (i32.const 0)
    (global.get $global0)
    (ref.func $"foo tear-off dynamic call entry")
    (ref.func $"foo tear-off trampoline_328")
    (struct.new $#Vtable-0-2)
    (i32.const 12)
    (i32.const 0)
    (i32.const 0)
    (global.get $"WasmArray<_Type>[0]")
    (global.get $"WasmArray<_Type>[0]")
    (global.get $_TopType_354)
    (global.get $_InterfaceType_30)
    (i32.const 10)
    (i32.const 0)
    (i32.const 1)
    (i32.const 156)
    (global.get $"WasmArray<_Type>[0]")
    (struct.new $_InterfaceType)
    (array.new_fixed $Array<_Type> 2)
    (i64.const 1)
    (global.get $"WasmArray<_NamedParameter>[0]")
    (struct.new $_FunctionType)
    (struct.new $#Closure-0-2))
  (global $_InterfaceType_30 (ref $_InterfaceType) <...>)
  (global $_InterfaceType_360 (ref $_InterfaceType) <...>)
  (global $_TopType_354 (ref $_TopType) <...>)
  (global $global0 (ref $#DummyStruct) <...>)
  (func $bar tear-off dynamic call entry (param $var0 (ref $#Closure-0-0)) (param $var1 (ref $Array<_Type>)) (param $var2 (ref $Array<Object?>)) (param $var3 (ref $Array<Object?>)) (result (ref null $#Top)) <...>)
  (func $bar tear-off trampoline_334 (param $var0 (ref struct)) (param $var1 (ref null $#Top)) (param $var2 (ref null $#Top)) (result (ref null $#Top)) <...>)
  (func $foo tear-off dynamic call entry (param $var0 (ref $#Closure-0-0)) (param $var1 (ref $Array<_Type>)) (param $var2 (ref $Array<Object?>)) (param $var3 (ref $Array<Object?>)) (result (ref null $#Top)) <...>)
  (func $foo tear-off trampoline_328 (param $var0 (ref struct)) (param $var1 (ref null $#Top)) (param $var2 (ref null $#Top)) (result (ref null $#Top)) <...>)
)