name: api_summary
version: 0.1.0-wip
description: Creates an API summary for a package.
publish_to: none

environment:
  sdk: '^3.12.0-0'

resolution: workspace

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analyzer: any
  collection: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  analyzer_testing: any
  dart_flutter_team_lints: any
  test: any
  test_reflective_loader: any
