#!/usr/bin/env python
# Copyright 2017 The Dart project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Forwards to the clang-format for the Linux toolchain."""

import os
import subprocess
import sys

DART_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLCHAIN = os.path.join(DART_ROOT, 'buildtools', 'toolchain')
CLANG_FORMAT = os.path.join(TOOLCHAIN, 'clang+llvm-x86_64-linux', 'bin', 'clang-format')

def main(argv):
  return subprocess.call([CLANG_FORMAT] + argv[1:])

if __name__ == '__main__':
  sys.exit(main(sys.argv))
