#!/bin/bash
# Run pub.dart on the Dart VM. This script assumes the Dart SDK's directory
# structure.

# Setting BIN_DIR this way is ugly, but is needed to handle the case where
# dart-sdk/bin has been symlinked to. On MacOS, readlink doesn't work
# with this case.
BIN_DIR="$(cd "${0%/*}" ; pwd -P)"
export DART_SDK="$(cd "${BIN_DIR%/*}" ; pwd -P)"

exec "$BIN_DIR"/dart "$DART_SDK"/util/pub/pub.dart $@
