class C;
class C extends O;
class C extends O implements I;
class C extends O with M implements I;
class C extends O with M;
class C implements I;
class C with M implements I;
class C with M;
class C<T>;
class C<T> extends O<T>;
class C<T> extends O<T> implements I<T>;
class C<T> extends O<T> with M<T> implements I<T>;
class C<T> extends O<T> with M<T>;
class C<T> implements I<T>;
class C<T> with M<T> implements I<T>;
class C<T> with M<T>;
class C();
class C() extends O;
class C() extends O implements I;
class C() extends O with M implements I;
class C() extends O with M;
class C() implements I;
class C() with M implements I;
class C() with M;
class C<T>();
class C<T>() extends O<T>;
class C<T>() extends O<T> implements I<T>;
class C<T>() extends O<T> with M<T> implements I<T>;
class C<T>() extends O<T> with M<T>;
class C<T>() implements I<T>;
class C<T>() with M<T> implements I<T>;
class C<T>() with M<T>;
class const C();
class const C() extends O;
class const C() extends O implements I;
class const C() extends O with M implements I;
class const C() extends O with M;
class const C() implements I;
class const C() with M implements I;
class const C() with M;
class const C<T>();
class const C<T>() extends O<T>;
class const C<T>() extends O<T> implements I<T>;
class const C<T>() extends O<T> with M<T> implements I<T>;
class const C<T>() extends O<T> with M<T>;
class const C<T>() implements I<T>;
class const C<T>() with M<T> implements I<T>;
class const C<T>() with M<T>;
class C.named();
class C.named() extends O;
class C.named() extends O implements I;
class C.named() extends O with M implements I;
class C.named() extends O with M;
class C.named() implements I;
class C.named() with M implements I;
class C.named() with M;
class C<T>.named();
class C<T>.named() extends O<T>;
class C<T>.named() extends O<T> implements I<T>;
class C<T>.named() extends O<T> with M<T> implements I<T>;
class C<T>.named() extends O<T> with M<T>;
class C<T>.named() implements I<T>;
class C<T>.named() with M<T> implements I<T>;
class C<T>.named() with M<T>;
class const C.named();
class const C.named() extends O;
class const C.named() extends O implements I;
class const C.named() extends O with M implements I;
class const C.named() extends O with M;
class const C.named() implements I;
class const C.named() with M implements I;
class const C.named() with M;
class const C<T>.named();
class const C<T>.named() extends O<T>;
class const C<T>.named() extends O<T> implements I<T>;
class const C<T>.named() extends O<T> with M<T> implements I<T>;
class const C<T>.named() extends O<T> with M<T>;
class const C<T>.named() implements I<T>;
class const C<T>.named() with M<T> implements I<T>;
class const C<T>.named() with M<T>;
