# Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

# Write code that's not supported in the language version used
# then change only the package config to change the language version.

type: newworld
worlds:
  - entry: package:foo/a.dart
    sources:
      .dart_tool/package_config.json: |
        {
          "configVersion": 2,
          "packages": [
            {
              "name": "foo",
              "rootUri": "../foo",
              "packageUri": "lib",
              "languageVersion": "3.12"
            }
          ]
        }
      foo/lib/a.dart: |
        class A {
          new() {
            print("A");
          }
        }
        void main() {
          A();
        }
    expectedLibraryCount: 1
    errors: true

  - entry: package:foo/a.dart
    worldType: updated
    expectInitializeFromDill: false
    invalidate:
      - .dart_tool/package_config.json
    sources:
      .dart_tool/package_config.json: |
        {
          "configVersion": 2,
          "packages": [
            {
              "name": "foo",
              "rootUri": "../foo",
              "packageUri": "lib",
              "languageVersion": "3.13"
            }
          ]
        }
    expectedLibraryCount: 1
    advancedInvalidation: packageUpdate
