# Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

# If the package config goes away and comes back we should recover.

type: newworld
worlds:
  - entry: main.dart
    packageConfigFile: .dart_tool/package_config.json
    sources:
      .dart_tool/package_config.json: |
        {
          "configVersion": 2,
          "packages": [
            {
              "name": "foo",
              "rootUri": "../foo",
              "packageUri": "lib"
            }
          ]
        }
      main.dart: |
        import "package:foo/a.dart";
        void main() {
          hello();
        }
      foo/lib/a.dart: |
        void hello() {
          print("hello v1");
        }
    expectedLibraryCount: 2

  - entry: main.dart
    packageConfigFile: .dart_tool/package_config.json
    worldType: updated
    errors: true
    expectInitializeFromDill: false
    invalidate:
      - .dart_tool/package_config.json
    deletedSources:
      - .dart_tool/package_config.json
    expectedLibraryCount: 1
    noErrorWarningCheckOnExtraCompiles: true
    advancedInvalidation: packageUpdate

  - entry: main.dart
    packageConfigFile: .dart_tool/package_config.json
    worldType: updated
    errors: false
    expectInitializeFromDill: false
    invalidate:
      - .dart_tool/package_config.json
    sources:
      .dart_tool/package_config.json: |
        {
          "configVersion": 2,
          "packages": [
            {
              "name": "foo",
              "rootUri": "../foo",
              "packageUri": "lib"
            }
          ]
        }
    expectedLibraryCount: 2
    noErrorWarningCheckOnExtraCompiles: true
    advancedInvalidation: packageUpdate
