#!/bin/bash

# To generate docs for a library, run this script with the path to an entrypoint
# .dart file, like:
#
# $ dartdoc foo.dart

# Get the .dart lib file the user wants to generate docs for.
entrypoint=$PWD/$1

# Run from dartdoc directory to get correct relative paths.
pushd `dirname "$0"` >>/dev/null

# Generate the client-side .js file from interact.dart if we haven't already or
# if it's out of date.
if [ "interact.dart" -nt "static/interact.js" ]
  then
  ../../frog/minfrog --libdir=../../frog/lib \
    --out=static/interact.js --compile-only interact.dart
  echo "Compiled interact.dart."
fi

# Ditch the first arg so we can pass any extra arguments to dartdoc.
shift

# Generate the user's docs.
../../frog/minfrog --libdir=../../frog/lib dartdoc.dart "$entrypoint" $@

popd >>/dev/null